### ISSUE TITLE
Installation failing on Meshes0 and Meshes1

### ISSUE THREAD

**Issue by jonathonwood** [Guitarninja2/septimus#110]
Down to the last hashing steps and Wabba keeps failing on the Mesh0 and Mesh1 files. I can see them in the download list but no joy. I've also tried copying over from the base Skyrim data folder (and tried renaming them from Skyrim - Meshes0.bsa to Data_Skyrim - Meshes0.bsa) and tried archiving the files but still cannot get the installer to proceed.

Relevant section from logs:
310.45 - Loaded permissions for 622 servers and 272 Google Drive files
310.45 - File hash check (-42) 550f415114beca0d3da30191dbb686849ad3980d5f3f38b1349bb95c66f2b309
310.5 - Downloading Data_Skyrim - Meshes1.bsa
310.5 - Downloading Data_Skyrim - Meshes0.bsa
313.04 - Hashed download is incorrect
313.04 - Loading for alternative to TvzBPkbzJjI=
313.07 - No alternative for TvzBPkbzJjI= could be found
317.91 - Hashed download is incorrect
317.91 - Loading for alternative to oIYZPu4jH2g=
317.95 - No alternative for oIYZPu4jH2g= could be found
317.97 - Hashing Remaining Archives
317.97 - Looking for files to hash
318.06 - Found 1412 total files, 1159 matching filesize
318.18 - Unable to download Data_Skyrim - Meshes0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - meshes0.bsa)
318.18 - Unable to download Data_Skyrim - Meshes1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - meshes1.bsa)
318.18 - Cannot continue, was unable to download one or more archives
318.18 - File hash check (-42) 550f415114beca0d3da30191dbb686849ad3980d5f3f38b1349bb95c66f2b309
318.18 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 217
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
318.51 - File hash check (-42) 550f415114beca0d3da30191dbb686849ad3980d5f3f38b1349bb95c66f2b309

**Comment by Guitarninja2** [comment]
Is your game fully up to date? Try verifying the files in steam and then running it again.

**Comment by jonathonwood** [comment]
That seems to have done the trick. 9 files needed updates. Weird because I had just updated to the latest patch, but we are now onto the extracting step. Thanks for the good advice!!
